import React, { useState } from 'react';
import { Wind, Thermometer, Gauge, Sparkles, Activity, CheckCircle2, ArrowUp, Sun } from 'lucide-react';
import { StructuralMetrics } from '../types';

interface AirflowThermodynamicsProps {
  metrics: StructuralMetrics;
}

export const AirflowThermodynamics: React.FC<AirflowThermodynamicsProps> = ({ metrics }) => {
  const [ambientTempC, setAmbientTempC] = useState<number>(24);
  const [internalTempC, setInternalTempC] = useState<number>(31); // Heat generated by bulb respiration & solar roof load
  const [externalHumidity, setExternalHumidity] = useState<number>(60);
  const [windSpeedKmH, setWindSpeedKmH] = useState<number>(12);
  const [louverOpeningPercent, setLouverOpeningPercent] = useState<number>(85);

  // Stack Effect (Efeito Chaminé) Physics Formula:
  // Q = Cd * A * sqrt(2 * g * h * (Ti - Te) / Ti)
  const g = 9.81; // Gravity m/s²
  const h = metrics.ridgeHeightMeters; // 18.0m effective height
  const TiKelvin = internalTempC + 273.15;
  const TeKelvin = ambientTempC + 273.15;
  const deltaT = Math.max(0.5, internalTempC - ambientTempC);

  // Louver inlet area across 120m both sides
  const baseInletAreaM2 = 120 * 2 * 0.8; // 192 m² total louvers
  const effectiveInletAreaM2 = baseInletAreaM2 * (louverOpeningPercent / 100);
  const cd = 0.62; // Discharge coefficient for timber louvers

  // Convective airflow speed at vents (m/s)
  const airflowSpeedMs = cd * Math.sqrt(2 * g * h * (deltaT / TiKelvin)) + (windSpeedKmH / 3.6) * 0.15;
  // Volumetric flow rate (m³/s and m³/h)
  const flowRateM3PerSecond = (effectiveInletAreaM2 * 0.35) * airflowSpeedMs;
  const flowRateM3PerHour = flowRateM3PerSecond * 3600;

  // Air changes per hour (Renovações de Ar por Hora - ACH)
  // Volume of building: 120m * 38m * 16.5m (avg height) = ~75.240 m³
  const buildingVolumeM3 = metrics.lengthMeters * metrics.widthMeters * 16.5;
  const airChangesPerHour = flowRateM3PerHour / buildingVolumeM3;

  return (
    <div className="flex flex-col h-full bg-[#0F0F0F] overflow-y-auto p-4 sm:p-6 text-[#E5E7EB]">
      {/* Top Banner */}
      <div className="flex flex-wrap items-center justify-between gap-4 mb-6 bg-[#1A1A1A] p-5 rounded border border-[#2D2D2D] shadow-xs">
        <div>
          <div className="flex items-center gap-2">
            <span className="px-2.5 py-0.5 rounded bg-[#0F0F0F] text-[#38bdf8] font-mono text-xs font-bold border border-[#2D2D2D]">
              TERMODINÂMICA PASSIVA & FLUIDODINÂMICA
            </span>
            <span className="text-xs text-[#6B7280] font-mono">EFEITO CHAMINÉ (CONVECÇÃO NATURAL)</span>
          </div>
          <h2 className="text-2xl font-serif font-bold text-[#D4A373] mt-1">
            Simulador de Ventilação Natural e Renovação de Ar
          </h2>
          <p className="text-xs text-[#9CA3AF]">
            Cálculo em tempo real do empuxo térmico gerado pela diferença de densidade do ar e desnível de 18 metros até a cumeeira.
          </p>
        </div>
      </div>

      {/* Primary KPI Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
        <div className="bg-[#1A1A1A] p-4 rounded border border-[#2D2D2D] shadow-xs">
          <div className="flex items-center justify-between text-[#9CA3AF] text-xs font-medium mb-1">
            <span>Vazão Volumétrica de Ar (Q)</span>
            <Wind className="w-4 h-4 text-[#38bdf8]" />
          </div>
          <div className="text-2xl font-bold text-[#38bdf8] font-mono">
            {Math.round(flowRateM3PerHour).toLocaleString('pt-BR')} <span className="text-sm font-normal text-[#9CA3AF]">m³/h</span>
          </div>
          <div className="text-xs text-[#9CA3AF] mt-1">
            Sem custo com ventiladores industriais
          </div>
        </div>

        <div className="bg-[#1A1A1A] p-4 rounded border border-[#2D2D2D] shadow-xs">
          <div className="flex items-center justify-between text-[#9CA3AF] text-xs font-medium mb-1">
            <span>Taxa de Renovação de Ar</span>
            <Gauge className="w-4 h-4 text-[#4ade80]" />
          </div>
          <div className="text-2xl font-bold text-[#4ade80] font-mono">
            {airChangesPerHour.toFixed(1)} <span className="text-sm font-normal text-[#9CA3AF]">trocas/hora</span>
          </div>
          <div className="text-xs text-[#4ade80] font-semibold mt-1">
            Ideal p/ secagem de ramas (&gt; 4 ACH)
          </div>
        </div>

        <div className="bg-[#1A1A1A] p-4 rounded border border-[#2D2D2D] shadow-xs">
          <div className="flex items-center justify-between text-[#9CA3AF] text-xs font-medium mb-1">
            <span>Velocidade Média nos Varais</span>
            <Activity className="w-4 h-4 text-[#D4A373]" />
          </div>
          <div className="text-2xl font-bold text-white font-mono">
            {airflowSpeedMs.toFixed(2)} <span className="text-sm font-normal text-[#9CA3AF]">m/s</span>
          </div>
          <div className="text-xs text-[#9CA3AF] mt-1">
            Velocidade laminar suave sem dessecar
          </div>
        </div>

        <div className="bg-[#1A1A1A] p-4 rounded border border-[#2D2D2D] shadow-xs">
          <div className="flex items-center justify-between text-[#9CA3AF] text-xs font-medium mb-1">
            <span>Gradiente Térmico (ΔT)</span>
            <Thermometer className="w-4 h-4 text-[#fb7185]" />
          </div>
          <div className="text-2xl font-bold text-white font-mono">
            +{deltaT.toFixed(1)} <span className="text-sm font-normal text-[#9CA3AF]">°C</span>
          </div>
          <div className="text-xs text-[#9CA3AF] mt-1">
            Pé-direito de 18m potencializa tiragem
          </div>
        </div>
      </div>

      {/* Simulator Sliders and Interactive Diagram */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Sliders Box */}
        <div className="bg-[#1A1A1A] p-5 rounded border border-[#2D2D2D] shadow-xs">
          <h3 className="text-base font-serif font-bold text-[#D4A373] mb-4 flex items-center gap-2">
            <Sun className="w-5 h-5 text-[#D4A373]" />
            Condições Climáticas e Operacionais
          </h3>

          <div className="space-y-4 text-xs">
            <div>
              <div className="flex justify-between font-semibold mb-1">
                <span className="text-[#E5E7EB]">Temperatura Ambiente Externa:</span>
                <span className="font-mono font-bold text-white">{ambientTempC} °C</span>
              </div>
              <input
                type="range"
                min="12"
                max="38"
                value={ambientTempC}
                onChange={(e) => {
                  const val = Number(e.target.value);
                  setAmbientTempC(val);
                  if (val >= internalTempC) setInternalTempC(val + 5);
                }}
                className="w-full accent-[#D4A373] cursor-pointer"
              />
            </div>

            <div>
              <div className="flex justify-between font-semibold mb-1">
                <span className="text-[#E5E7EB]">Temperatura na Cumeeira / Telhado:</span>
                <span className="font-mono font-bold text-[#fb7185]">{internalTempC} °C</span>
              </div>
              <input
                type="range"
                min={ambientTempC + 1}
                max="45"
                value={internalTempC}
                onChange={(e) => setInternalTempC(Number(e.target.value))}
                className="w-full accent-[#fb7185] cursor-pointer"
              />
            </div>

            <div>
              <div className="flex justify-between font-semibold mb-1">
                <span className="text-[#E5E7EB]">Abertura das Venezianas Laterais (120m):</span>
                <span className="font-mono font-bold text-[#38bdf8]">{louverOpeningPercent}% Abertas</span>
              </div>
              <input
                type="range"
                min="10"
                max="100"
                step="5"
                value={louverOpeningPercent}
                onChange={(e) => setLouverOpeningPercent(Number(e.target.value))}
                className="w-full accent-[#38bdf8] cursor-pointer"
              />
            </div>

            <div>
              <div className="flex justify-between font-semibold mb-1">
                <span className="text-[#E5E7EB]">Velocidade do Vento Externo:</span>
                <span className="font-mono font-bold text-white">{windSpeedKmH} km/h</span>
              </div>
              <input
                type="range"
                min="0"
                max="40"
                value={windSpeedKmH}
                onChange={(e) => setWindSpeedKmH(Number(e.target.value))}
                className="w-full accent-[#9CA3AF] cursor-pointer"
              />
            </div>
          </div>
        </div>

        {/* Physics Explanation Card */}
        <div className="bg-[#1A1A1A] p-5 rounded border border-[#2D2D2D] shadow-xs flex flex-col justify-between">
          <div>
            <h3 className="text-base font-serif font-bold text-[#D4A373] mb-3 flex items-center gap-2">
              <Sparkles className="w-5 h-5 text-[#38bdf8]" />
              Princípio Aerodinâmico e Vantagens Econômicas
            </h3>
            <p className="text-xs text-[#9CA3AF] leading-relaxed mb-3">
              O galpão atua como uma chaminé térmica gigante. O ar mais frio e denso entra pelas venezianas inferiores de 120m, absorve a umidade desprendida pelas réstias de alho e se aquece pela irradiação da cobertura e calor biológico. O ar úmido e quente torna-se mais leve e sobe espontaneamente a 18 metros de altura, saindo pela cumeeira.
            </p>

            <div className="space-y-2 text-xs">
              <div className="flex items-start gap-2 p-3 bg-[#122218] rounded border border-[#4ade80]/30">
                <CheckCircle2 className="w-4 h-4 text-[#4ade80] mt-0.5 shrink-0" />
                <div className="text-[#E5E7EB]">
                  <strong className="text-[#4ade80]">Zero Custo de Energia Elétrica:</strong> Economia estimada de R$ 120.000 a R$ 180.000 por safra em comparação com secadores forçados elétricos ou a gás.
                </div>
              </div>

              <div className="flex items-start gap-2 p-3 bg-[#102230] rounded border border-[#38bdf8]/30">
                <CheckCircle2 className="w-4 h-4 text-[#38bdf8] mt-0.5 shrink-0" />
                <div className="text-[#E5E7EB]">
                  <strong className="text-[#38bdf8]">Qualidade Superior do Bulbo:</strong> Secagem lenta e uniforme (3 a 5 semanas) preserva os óleos essenciais (alicina), cor natural e firmeza das cascas.
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
